apiVersion: v1
kind: Secret
metadata:
  name: consumer-connection-string
  namespace: lab
type: opaque
# Event hubs connections shared access police with entity Path ex:
stringData:
  CONNECTIONSTRING: "Endpoint=sb://<mybus>.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=<mnykey>=;EntityPath=medium.rocks"
---
apiVersion: v1
kind: Secret
metadata:
  name: producer-connection-string
  namespace: lab
type: opaque
# Event hubs connections shared access police without entity Path ex:
stringData:
  CONNECTIONSTRING: "Endpoint=sb://<mybus>.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=<mykey>="
